# CMake generated Testfile for 
# Source directory: /home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests
# Build directory: /home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Runs "/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/Tutorial" "25")
set_tests_properties(Runs PROPERTIES  _BACKTRACE_TRIPLES "/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;43;add_test;/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;0;")
add_test(Usage "/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/Tutorial")
set_tests_properties(Usage PROPERTIES  PASS_REGULAR_EXPRESSION "Usage:.*number" _BACKTRACE_TRIPLES "/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;46;add_test;/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;0;")
add_test(Comp4 "/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/Tutorial" "4")
set_tests_properties(Comp4 PROPERTIES  PASS_REGULAR_EXPRESSION "4 is 2" _BACKTRACE_TRIPLES "/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;53;add_test;/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;60;do_test;/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;0;")
add_test(Comp9 "/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/Tutorial" "9")
set_tests_properties(Comp9 PROPERTIES  PASS_REGULAR_EXPRESSION "9 is 3" _BACKTRACE_TRIPLES "/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;53;add_test;/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;61;do_test;/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;0;")
add_test(Comp5 "/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/Tutorial" "5")
set_tests_properties(Comp5 PROPERTIES  PASS_REGULAR_EXPRESSION "5 is 2.236" _BACKTRACE_TRIPLES "/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;53;add_test;/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;62;do_test;/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;0;")
add_test(Comp7 "/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/Tutorial" "7")
set_tests_properties(Comp7 PROPERTIES  PASS_REGULAR_EXPRESSION "7 is 2.645" _BACKTRACE_TRIPLES "/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;53;add_test;/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;63;do_test;/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;0;")
add_test(Comp25 "/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/Tutorial" "25")
set_tests_properties(Comp25 PROPERTIES  PASS_REGULAR_EXPRESSION "25 is 5" _BACKTRACE_TRIPLES "/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;53;add_test;/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;64;do_test;/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;0;")
add_test(Comp-25 "/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/Tutorial" "-25")
set_tests_properties(Comp-25 PROPERTIES  PASS_REGULAR_EXPRESSION "-25 is [-nan|nan|0]" _BACKTRACE_TRIPLES "/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;53;add_test;/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;65;do_test;/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;0;")
add_test(Comp0.0001 "/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/Tutorial" "0.0001")
set_tests_properties(Comp0.0001 PROPERTIES  PASS_REGULAR_EXPRESSION "0.0001 is 0.01" _BACKTRACE_TRIPLES "/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;53;add_test;/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;66;do_test;/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;0;")
add_test(Comp4096 "/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/Tutorial" "4096")
set_tests_properties(Comp4096 PROPERTIES  PASS_REGULAR_EXPRESSION "4096 is 64" _BACKTRACE_TRIPLES "/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;53;add_test;/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;67;do_test;/home/hotopb/Dropbox/Spring 2021/Open Source Software/labs/dump/lab07/help/cmake-tests/CMakeLists.txt;0;")
subdirs("MathFunctions")
